### ISSUE TITLE
Add SSHRC Logo to page

### ISSUE THREAD

**Issue by rcastong** [sfu-dhil/wphp#210] opened 2021-01-19 20:45 UTC
Add this at bottom of homepage (?)
![image](https://user-images.githubusercontent.com/57373524/105091020-1326e180-5a54-11eb-8f4a-0ec148006608.png)
@mnl101 where did you take this originally? Joey will probably the original... Thx!

**Comment by joeytakeda** [comment] 2021-01-19 20:56
This is a duplicate of #200, I think, so I'm going to close this (unless I'm missing something here--feel free to re-open if this is distinct).

In terms of the graphic, we have a number of the SSHRC assets in the DHIL's Drive already (with transparencies etc). I think we have this one, but, if not, I'll retrieve it from SSHRC's asset listing on their website.

**Closed by joeytakeda** 2021-01-19 20:56 UTC
