### ISSUE TITLE
ESTC import function creating new person records for authors even when we already have them in the database. 

### ISSUE THREAD

**Issue by mnl101** [sfu-dhil/wphp#162] opened 2020-07-13 20:06 UTC
Describe the bug:
The ESTC import function creates a new person record for the author indicated by the ESTC, using the ESTC information about that person (birth and death dates, basically). It does this even when we have a pre-existing person record for that individual.

To reproduce:
Click “Explore”, then click “ESTC” from the drop down menu
Click “Imprint Search”
Type “Alice James” (in quotations) in the search field and click “search”
Click ID “95981”
Click “Import”
You will see four messages at the top of the page, including one that says “No person record found for Gibson, Edmund. You may need to edit the person record after importing this title.” despite the fact that we already have this title in the database and already have a person record for Edmund Gibson. (see screenshot 1)
Click “search” in the top menu
Type “Gibson” in the search field and click search
There are multiple Edmund Gibsons - ID 4636 is the one that already existed, and ID 4676 is the new one that the import function just created (even though I did not actually create a title entry).

Expected results: 
A person record is created only if we don’t already have a person record for them in the database.

Additional context:
Screenshot 1:
![ESTC person bug screenshot 1](https://user-images.githubusercontent.com/62716954/87348408-85e55c00-c509-11ea-89a5-b5d77aa2fc23.png)

Screenshot 2:

![ESTC person bug screenshot 2](https://user-images.githubusercontent.com/62716954/87348440-91d11e00-c509-11ea-9cd9-2ec7e5ec3eb2.png)

**Comment by mnl101** [comment] 2021-01-21 18:11
Hi Michael, We are still having this same issue with a new person record being created even if one already exists. this has created a number of duplicates! Not sure why it was closed???

**Comment by mnl101** [comment] 2021-01-21 18:27
Note: Kate just attempted to follow the instructions above and it looks like because she imported that record already when she made that first bug report, ID 95981 doesn't show up in the import field anymore. However, she checked and a new person is being added with every record we attempt to import.

**Comment by ubermichael** [comment] 2021-01-26 21:00
The image you posted has ID 95181 instead of 95981. When I import 95181 I don't get a duplicate of Edmund Gibson. When I import 95981 I get a new record for Thomas Bish, but that's expected, since he wasn't already in the database. If I try to import 95981 a second time I don't get a duplicate for Thomas Bish. 

Can you give me a few examples of duplicate records created in this way, and the ESTC IDs of the imports that created them?

**Comment by mnl101** [comment] 2021-02-09 20:22
Still happening: When I import a title from the ESTC, it creates a person record for the author **even if we already have a person record for them**. Here is an example that should work for you:

To reproduce: 
Go to “Database” and click “ESTC” in the drop-down menu
Click “Imprint search”
Type in “Ann Ward”
Click title ID 52959 
Click “import”
The error messages will appear at the top. 
If you go to “Database” and click “Search Persons” and type in “Sterne”, you’ll now see two Laurence Sterne entries because we already had one (ID 4626) and the import function created a new, second one. 

Expected results: 
No new person record should ever be created when we import new title records. (Context: We think this may be happening because we cannot create title entries when there is not a person attached in the contributors field. If it is the case that we need a person record attached in order to import these titles, should we create a “default” person record (probably named something like ‘ESTC Import Person Record’) that gets attached to these instead, so we can follow up and do our own person record work once the title is imported?

Additional context: 
I have attached screenshots of an import of a different title to display the error messages that appear when we import something, including the one that says we may need to correct the person record. I’ve included a screenshot that shows we already had a John Garnett in the database before the import, but it created another one anyway. 

![import screenshot 1](https://user-images.githubusercontent.com/62716954/107423018-b063bb80-6ad0-11eb-8fa9-3beaa1c30fbe.png)

![import screesnshot 2](https://user-images.githubusercontent.com/62716954/107423072-c3768b80-6ad0-11eb-8727-14853019a6a0.png)

I’ve given you a different ID to use above to replicate this issue because once the ESTC import function has created a person once, the system recognizes that it’s already done that — it does not, however, recognize when we already had a pre-existing person record for that person, and I don’t think it’s possible for the system to do that given the complexities of names and name changes in our person record fields.There’s no way to guarantee it will match ESTC name data. The problem is that we are getting a lot of duplicate persons and that is really messing up our person data! So as we say above, the best way forward is for no person records to be added, ever, when using this function.

**Comment by ubermichael** [comment] 2021-02-18 18:27
The solution is to never ever create a person record when importing a MARC record.

**Closed** 2021-02-19 21:56 UTC
Labels: question
