### ISSUE TITLE
Change documentation embedded in site, under search boxes (for title, persons and firms), as per editorial changes suggested by Kim and Michelle

### ISSUE THREAD

**Issue by rcastong** [sfu-dhil/wphp#97] opened 2020-03-20 23:41 UTC
I believe this is mostly done but MJ might have a couple things to fix before ML can review

**Comment by ubermichael** [comment] 2020-03-20 23:42
This is a duplicate of https://github.com/sfu-dhil/wphp/issues/68 so I'm closing it.

**Closed by ubermichael** 2020-03-20 23:42 UTC
