### ISSUE TITLE
Cannot add pages to new Research menu

### ISSUE THREAD

**Issue by mnl101** [sfu-dhil/wphp#192] opened 2020-10-08 20:46 UTC
**Describe the bug**
We cannot add pages to research menu item.

**To Reproduce**
When you click on research (when logged in) you do not get a "All Pages" option like you do in about. "All Pages" allows us to add new pages.

**Expected behavior**
We should be able to add new pages to the Research menu item, as we can for About.

**Comment by rcastong** [comment] 2020-10-10 17:21
I noticed that, when not logged-in, the "Research" drop-down menu doesn't drop... When you are logged in you can drop it down but only one option ("All Research") is available.

**Comment by ubermichael** [comment] 2020-10-13 17:04
You can add a research page in the same way you add spotlight pages, but select Research as a category instead of one of the spotlight categories. I just tested it and it works.

@rcastong that's by design. There are no pages in the research category right now.

**Comment by mnl101** [comment] 2020-10-14 00:40
this works, thanks, but there is no way to sort the order of pages under research (as there is for about). Ideally we need this feature or we need to know how to create the pages so they sort properly.

<img width="1247" alt="Screen Shot 2020-10-13 at 5 38 51 PM" src="https://user-images.githubusercontent.com/62716954/95930328-0c187500-0d7b-11eb-9712-504ab4930cb0.png">

**Comment by ubermichael** [comment] 2020-10-14 18:17
The research menu and posts on the All Research page are ordered by date.

**Comment by mnl101** [comment] 2020-10-14 18:53
So most recently added is at the top?

**Comment by ubermichael** [comment] 2020-10-14 22:21
That’s correct. Most recent first.

**Comment by mnl101** [comment] 2020-10-14 23:08
Sorry, another problem. I just created a few pages and put the category as research. However, these pages are showing up under news. So I deleted them as we don’t want that. These are static pages that should appear under research menu only not be part of the blog posts listed under news. Unless I am missing something, I think we need for research what we have for the about page; the ability to add and move pages, that appear only under that menu item.

**Comment by ubermichael** [comment] 2020-10-15 17:02
I hadn't properly excluded Research from the News menu. That error should be fixed in a few minutes.

**Comment by ubermichael** [comment] 2020-10-16 18:41
@mnl101 can you give it a try? If it works please close this issue. If it doesn't please add an additional comment here.

**Comment by mnl101** [comment] 2020-10-16 19:47
Hi Michael, unfortunately I cannot log in now (neither can Sara, and I haven’t asked the other RAs yet).  We noticed this late yesterday, and assumed you were doing some work. Here is what the screen shows. I have definitely not reset my password!

Michelle

**Comment by ubermichael** [comment] 2020-10-16 20:01
It looks like the database update has messed something up. I was able to login, but only after resetting my password. I think everyone is going to require a password reset.

**Closed** 2020-11-03 23:33 UTC
